ALTER TABLE tournament_matches
ADD COLUMN IF NOT EXISTS player1_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS player2_score INTEGER DEFAULT 0;

ALTER TABLE tournaments
ADD COLUMN IF NOT EXISTS rounds_to_win INTEGER DEFAULT 1;
